- src/Client.js
- src/GitWrapper.js
- src/Sync.js
> Added logic to verify scopes of token before running

- src/GitWrapper.js
- src/rename.js
Added script that will rename projects based on what they are projected
to be.
> Added rename script to src folder

- src/GitWrapper.js
- src/Sync.js
- src/rename.js
> Rename + sync update for visibility

- src/Sync.js
> Removed test data

- src/Sync.js
> Removed behaviour to remove users from teams

- k8s/cronjob.yml
> Release on production

- src/Sync.js
> Fix logging statement

- src/Sync.js
> Add null pointer catch to regex match for GitHub url

- src/Sync.js
> Fix for change in github_repos structure from Eclipse API

- src/Sync.js
Fixed org/repo regex to allow for trailing slashes, additional checks
for user github handle to check for empty values.
> Added additional logging, fixes to some small issues

- k8s/cronjob.yml
> remove dry-run for real this time

- src/GitWrapper.js
- src/member-report.js
> Added member report script

- src/member-report.js
> Fix for case sensitive comparisons of GitHub IDs in member report

- .gitignore
- .travis.yml
> add travis.yml config file

- src/HttpWrapper.js
> Add logging to getRaw error state for http wrapper

- README.md
- src/GitWrapper.js
- src/Sync.js
- src/repo-report.js
> Added repo report for checking for bot users + outside contributors

- src/GitWrapper.js
- src/Sync.js
> Feature Request for GitHub Sync script - Give every project lead...#41

- package-lock.json
> Fix for CVE-2020-7598: Minimalist package

- src/reports/org-perm-report.js
Fixed spacing + added config for throttle time.
> Add throttle config value to org permission report

- .gitignore
- Dockerfile.gitlab
- Jenkinsfile
- k8s/gitlab.cronjob.yml
- package-lock.json
- package.json
- src/EclipseAPI.js
- src/gitlab-sync.js
- test/EclipseAPITest.js
- test/HttpWrapperTest.js
Initial work done for GitLab sync script. Contains 95% of work needed
for GitLab syn script to function. Requires secret setup +
Jenkins/travis/k8s setup to make use of multiple/chained jobs.
> GitLab sync integration created

- src/EclipseAPI.js
- src/gitlab-sync.js
> Fix for wrong field being checked for repos in GitLab sync

- test/EclipseAPITest.js
> Fix test that is failing from previous patch

- Dockerfile.gitlab
- src/gitlab-sync.js
> Set GitLab sync to staging for testing

- src/EclipseAPI.js
- src/gitlab-sync.js
> Added and improved logging for GitLab sync

- src/gitlab-sync.js
> Fix for user email + project ID used for group creation

- src/gitlab-sync.js
> Updated group creation/tracking for GL sync

- src/gitlab-sync.js
> Fix for project name collision

- k8s/gitlab.cronjob.yml
> Update kubernetes descriptor/config for production

- src/gitlab-sync.js
Fixes #64. Added try catches, removed system exit on call failures.
Includes whitespace formatting fixes.
> GL sync script is failing out on error instead of just logging #64

- README.md
- package-lock.json
- package.json
- src/EclipseAPI.js
- src/gitlab-sync.js
Fixes #56. Added oauth module to npm package. Updated EclipseAPI class
to obfuscate client secrets after being set through constructor.
Authentication for users fetch added, to retrieve email.
> Update user creation to set users correct email rather than dummy... #56

- k8s/gitlab.cronjob.yml
- src/gitlab-sync.js
> Update GL k8s config to use new secret #56

- k8s/gitlab.cronjob.yml
> Update to use separate secret volume for oauth config in k8s

- src/Sync.js
> Fix for bad logger call in Github sync script

- src/Sync.js
> Fix refactor error in js (result should be r)

- Dockerfile
- Dockerfile.gitlab
- k8s/cronjob.yml
- k8s/gitlab.cronjob.yml
- src/EclipseAPI.js
- src/reports/member-report.js
- src/reports/repo-report.js
> Fix for bad logging calls for not present method

- .eslintrc.json
- Jenkinsfile
- NOTICE.md
- package-lock.json
- package.json
- src/Client.js
- src/EclipseAPI.js
- src/GitWrapper.js
- src/HttpWrapper.js
- src/Sync.js
- src/TimeCache.js
- src/gitlab-sync.js
- src/reports/member-report.js
- src/reports/org-perm-report.js
- src/reports/repo-report.js
Used preset configs from strongloop as base for linting strategy. Fixed
issues such as duplicate vars, unused variables, and some equation
checks.
> Add linting to project on test, fix the errors declared from linting

- src/GitlabSync.js
- src/SecretReader.js
- src/Sync.js
- test/SecretReaderTest.js
- test/secrets/non-utf-file
- test/secrets/sample-secret
> Centralize Kubernetes secret reading functionality #83

- package-lock.json
- package.json
- src/GitWrapper.js
- src/Sync.js
- src/reports/MemberReport.js
Added verbose method entry level logging, and updated to v18 of rest.js
for Octokit.
Fixes #77
> Upgrade to newest stable version of Octokit REST.js #77

- .eslintrc.json
- src/EclipseAPI.js
- src/GitWrapper.js
- src/GitlabSync.js
- src/HttpWrapper.js
- src/SecretReader.js
- src/Sync.js
- src/TimeCache.js
- src/reports/MemberReport.js
- src/reports/OrgPermissionReport.js
- src/reports/RepositoryReport.js
> Investigate Strongloop eslint config #88

- src/EclipseAPI.js
- src/Sync.js
- src/reports/MemberReport.js
- src/reports/OrgPermissionReport.js
- src/reports/RepositoryReport.js
- test/EclipseAPITest.js
> Finish migrating EclipseAPI functionality

- src/GitWrapper.js
- src/Sync.js
> Add more verbose logging

- src/Sync.js
> Feature Request for GitHub Sync script - Give every project lead ...#41

- src/teams/static.json
> Update team to include additional users

- src/Sync.js
> Added additional verbosity around updates to team permissions

- src/GitWrapper.js
- src/Sync.js
Fix for async processing not using "await", fix for failing external
contributor culling calls.
> Patches for live running dev merge

- src/GitWrapper.js
- src/reports/MemberReport.js
> Fix for null return instead of undefined

- src/Sync.js
> Add flag to not overwrite project lead permissions

- src/GitlabSync.js
> Fix for bots not being respected

- src/teams/static.json
Fix #126 
Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>
> Add shanda to eclipsefdn-staff team #126

- src/teams/static.json
> Add Mehrnaz to Github team

- src/teams/static.json
> remove Ioana

- src/gh/BotFix.js
Requires an admin API token for GH w/ access to all of our orgs.
> Add script to fix bot permissions for all bots

- src/Sync.js
> Remove fatal exit on 404 as it should be handled more gracefully

- src/GitlabSync.js
> Update PL level to maintainer from previous access level

- README.md
> Update to the sync docs for feedback

- src/Sync.js
> Add user removal back, checking for bots before deleting

- package-lock.json
- package.json
- src/EclipseAPI.js
- src/GitWrapper.js
- src/GitlabSync.js
- src/HttpWrapper.js
- src/SecretReader.js
- src/Sync.js
- src/logger.js
- src/teams/StaticTeamManager.js
Update all current scripts to use Winston rather than console logging.
This allows for additional information in the log, and concurrent
writing to file as well as console.
> Update logging to use Winston

- README.md
- package-lock.json
- package.json
Holding on merging this PR until the big ticket items have been confirmed as working. Will be authoring tagging guide following this patch (will use the npm convention as a base line, as it lgtm. Beta only used as we are pre stable still).
> Bump version to 1.0.0-BETA and tidy package

- Jenkinsfile
- src/auto_backup/ImportRunner.js
- test/ImportRunnerTest.js
- Fix NPE on backup import
- Add logic to deal with leading 0s in group name
- Fix call to Groups API to use proper subgroups call
- Add unit testing for group name
> Bug fixes for import code

- k8s/import.cronjob.yml
Note that secrets still need to be updated
> Update import Cron to point at production

- src/teams/static.json
Add Hailley Seed to team static config.
> Being added to the Eclipse Page #187

- Jenkinsfile
> Update credentials for both cronjobs deployment

- src/teams/static.json
> Update to the EF staff static list #200
