EclipseFdn/eclipsefdn-github-sync

Jenkinsfile
k8s/cronjob.yml

This enables CI/CD for this repo (see issue #14).
The k8s cronjob is scheduled to run every 20min. We can customize this in k8s/cronjob.yml with the `schedule: "*/20 * * * *"`
It also does not allow concurrent run: if it is time for a new job run and the previous job run hasn’t finished yet, the cron job skips the new job run
It currently runs with options `--verbose=true --dryrun=true` (again see k8s/cronjob.yml).
Logs are stored on `nfsmaster:/opt/export/eclipsefdn-github-sync/logs` and we need to find a way to make them available to webdev team. Note that stdout is tee'd to `/app/logs/stdout-$(date +%Y%m%d).log`
The api-token is currently a randomly generated one (hence fake). Feel free to send me any other token that you would like to use.
The Jenkinsfile build and push images for all …

Added k8s cronjob and Jenkinsfile

---

docker-compose.yml
k8s/cronjob.yml
package.json
src/Client.js
src/Sync.js

The getUTCDay() method returns the day of the week (from 0 to 6) for the
specified date, according to universal time. We should use getUTCDate
since it returns the day of the month (from 1 to 31) of the date object,
according to universal time.

Fix log dates and dryrun is now the default

---

src/Sync.js

Fix project_id field to not reference project_project_id

---

src/Sync.js

Fix for no sanitization on team names for sync script on privacy fix

---

Dockerfile
src/Sync.js

First phase consists of checking Eclipse API and if we have a response
and can verify its the same user, they are then removed from the team.
Added new -D flag to run in semi dry mode, where only deletion is
limited.

Added first phase of Github user eviction

---

package-lock.json
package.json
src/GitWrapper.js
test/dev-data.js

Updated octokit to last v16 version, and plugins to last pre-3.0
versions. Octokit v17 introduces breaking changes across almost every
call, deprecating most calls used in this script. Deprecation messages
will be incredibly common in the script until this is fixed and will
polute logs. Updated code around team management to use pre-v17 code
that was erroneously included. Included a small JSON snip in the test
folder that contains development data pointed at the EclipseFdn sandbox
for easy access.

New project leads team does not have any repositories #47

---

src/GitWrapper.js
src/Sync.js
src/reports/member-report.js
src/reports/org-perm-report.js
src/reports/repo-report.js

Moved all reports to own folder. Created new report for checking org
permissions. Added new calls to retrieve orgs in git wrapper for new
report. Added function to update org permissions, using preview header
to allow more fields. Added call to new org update function in wrapper
when processing new orgs. This will only be performed when not in dry
run.

Repository creation for org members is enabled by default and... #51

---

.travis.yml
Dockerfile
Dockerfile.gitlab
src/EclipseAPI.js

Added default value for conig constructor arg of empty object. This
allows empty param constructors to build an unauthorized wrapper object.

Fix for failed tests in EclipseAPI test file

---

k8s/cronjob.yml

Fix based on code in the GL script which was updated in collaboration
with release folks.

Fix to allow GH sync logs to capture ERR OUT logs as well as STD

---

src/EclipseAPI.js
test/EclipseAPITest.js

Add option to bypass pagination for EclipseAPI. While this isn't useful
for production, this allows for safer testing. Update EclipseAPI tests
to use new pagination param to byass pagination when testing.
Include test for gitlab repos that was previously missed.
Fixes #95

Fix brittle test that causes build timeouts #95

---

src/Sync.js

Use no overwrite option for adding repo to team access permissions, with
default permissions of pull.
Fixes #50

Do not reset contributor team's permissions if it's set to "triage" #50

---

Dockerfile
Dockerfile.gitlab
Jenkinsfile

Jenkins seems to be deploying a cached version of the sync script.

use --no-cache when building docker image

---

src/GitlabSync.js

Move site endpoint of gitlab.eclipse.org that was passed to the
EclipseBots call to the processBots (where it is needed).

Fix processBots call to have the site endpoint

---

src/GitlabSync.js

Add period as an allowed character in group names, and fixed proj path

---

src/GitlabSync.js
src/Sync.js

This should have been removed in early iterations, but this was for
whatever reason kept around much longer. Since we allow bots at the
collaborator level, they shouldn't be in a team.

Remove the safeguard around user deletion for teams

---

src/Sync.js

Fix to use case insensitive check to remove found users in removal step

---

src/GitlabSync.js

Fix linting error in regex for useless escape character

---

src/Sync.js

Fixes #78
Removing last of SAB and atmoics check that were left after initial
sweep in Octokit upgrade.

Look into rate limiting through Octokit plugin and remove... #78

---

Jenkinsfile

Update Jenkins build to deploy for production branch rather than master

---

README.md

Add CLI parameter tables to the README for sync scripts

---

src/GitlabSync.js
src/Sync.js

Add project ID target as param in sync scripts.

Add parameter to sync runs to allow for targeting of a single ...#150

---

src/GitlabSync.js
src/HttpWrapper.js
src/logger.js
src/teams/StaticTeamManager.js
test/HttpWrapperTest.js

Only removes users that are directly set on projects that are not bots
or not admins.

Add check and cleanup operation on project permisions

---

k8s/import.cronjob.yml

Command had 2 --target values, which caused the GL api to refuse the values as invalid.

Fix multiple targets in cron import command
